/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JTableFenetres;
import Modele.ForMod.*;
import Modele.Initialisation.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author wafadjerir
 */
public class JTableCreaModule extends javax.swing.JFrame {

    /**
     * Creates new form JTableCreaModule
     */
    public JTableCreaModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFormation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboFormation = new javax.swing.JComboBox();
        textModule = new javax.swing.JTextField();
        textAbbrev = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textNbSeance = new javax.swing.JTextField();
        b_ajout = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_sauve = new javax.swing.JButton();
        comboCouleur = new javax.swing.JComboBox();
        msgNomFormation = new javax.swing.JLabel();
        messageErreur = new javax.swing.JLabel();
        msgDureeFormation = new javax.swing.JLabel();
        msgDureeSeanceFormation = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableFormation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module", "Abbréviation", "Couleur", "Nombre de seance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFormation.setGridColor(new java.awt.Color(0, 0, 0));
        jTableFormation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFormationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFormation);
        if (jTableFormation.getColumnModel().getColumnCount() > 0) {
            jTableFormation.getColumnModel().getColumn(0).setResizable(false);
            jTableFormation.getColumnModel().getColumn(1).setResizable(false);
            jTableFormation.getColumnModel().getColumn(2).setResizable(false);
            jTableFormation.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setText("       Choix des modules ");
        jLabel1.setMaximumSize(new java.awt.Dimension(165, 16));

        jLabel2.setText("Formation");

        jLabel3.setText("Abbréviation");

        jLabel4.setText("Nom Module");

        jLabel5.setText("Couleur");

        comboFormation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune ", "LICENCE 3", " " }));
        comboFormation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormationItemStateChanged(evt);
            }
        });

        textModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModuleActionPerformed(evt);
            }
        });

        textAbbrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAbbrevActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre de séances");

        b_ajout.setText("Ajouter");
        b_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ajoutActionPerformed(evt);
            }
        });

        b_delete.setText("Supprimer");
        b_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_deleteMouseClicked(evt);
            }
        });
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        b_update.setText("Mettre à jour");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_sauve.setText("Sauvegarder");
        b_sauve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sauveActionPerformed(evt);
            }
        });

        comboCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gris", "Rouge", "Vert", "Jaune", "Rose", "Violet", "Bleu", "Orange", " " }));
        comboCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCouleurActionPerformed(evt);
            }
        });

        msgNomFormation.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        msgNomFormation.setForeground(new java.awt.Color(0, 0, 255));
        msgNomFormation.setAlignmentX(10.0F);

        messageErreur.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        messageErreur.setForeground(new java.awt.Color(255, 51, 51));
        messageErreur.setAlignmentX(10.0F);

        msgDureeFormation.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        msgDureeFormation.setForeground(new java.awt.Color(0, 0, 255));
        msgDureeFormation.setAlignmentX(10.0F);

        msgDureeSeanceFormation.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        msgDureeSeanceFormation.setForeground(new java.awt.Color(0, 0, 255));
        msgDureeSeanceFormation.setAlignmentX(10.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboFormation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textModule, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textAbbrev, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNbSeance)
                            .addComponent(comboCouleur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(b_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(b_update)
                        .addGap(18, 18, 18)
                        .addComponent(b_sauve, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(msgDureeFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(msgDureeSeanceFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(msgNomFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(messageErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAbbrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textNbSeance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ajout)
                    .addComponent(b_delete)
                    .addComponent(b_update)
                    .addComponent(b_sauve))
                .addGap(18, 18, 18)
                .addComponent(msgNomFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgDureeSeanceFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgDureeFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(messageErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAbbrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAbbrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAbbrevActionPerformed

    private void textModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModuleActionPerformed
    
    private void b_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ajoutActionPerformed
        // Procédure d'ajout les lignes de Modules à la formation (Fenetre Creation des modules)
        //A COMPLETER POUR LES AUTRES ELEMENTS 
        messageErreur.setText("");//Vider le label Message
        DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
        if(comboFormation.getSelectedItem().toString().equals("LICENCE 3")){
            Formation licence3 = Insert.Inserer();
        if(!textModule.getText().trim().equals("") && !textAbbrev.getText().trim().equals("") && !textNbSeance.getText().trim().equals("")){
        if(licence3.testNom(textModule.getText()) == 0){
        if(licence3.testAbbrev(textAbbrev.getText()) == 0){
        if(licence3.testCouleur(comboCouleur.getSelectedItem().toString()) == 0 ){
        model.addRow(new Object[]{textModule.getText(),textAbbrev.getText(),comboCouleur.getSelectedItem().toString(),textNbSeance.getText() });
        Module module;
        module = new Module(textModule.getText(),textAbbrev.getText(),comboCouleur.getSelectedItem().toString(),Integer.parseInt(textNbSeance.getText()));
        ModuleFormation module_Formation = new ModuleFormation(module);
        licence3.getTabModule().add(module_Formation);
        licence3 = Insert.InserModule(module_Formation);
        messageErreur.setText("L'ajout du module "+ textModule.getText() +" a bien été effectué");
        
        }else{
            messageErreur.setText("WARNING CHOIX COULEUR! cette couleur existe déja");
        }
        
        }else{
            messageErreur.setText("WARNING CHOIX ABBREVIATION! Cette abbréviation existe déja");
        }
        
        
        }else{
             messageErreur.setText("WARNING CHOIX NOM! Ce nom existe déja");
        }
        
        
        
        }else {
            messageErreur.setText("WARNING CHAMPS VIDES! Veuillez remplier tous les champs pour pouvoir ajouter un nouveau module");
            
        }
        }else{
            messageErreur.setText("WARNING CHOIX FORMATION! Veuillez choisir la formation");
        }
    }//GEN-LAST:event_b_ajoutActionPerformed

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
            // Procédure pour supprimer un module 
        
        messageErreur.setText("");//Vider le label Message
        DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
        if(jTableFormation.getSelectedRow() == -1 ){
            if(jTableFormation.getRowCount() == 0){
                messageErreur.setText("WARNING DELETE! La table est vide");
            }else {
                 messageErreur.setText("WARNING DELETE! Vous devez selectionner au moins une ligne ");
            }
        }else {
        model.removeRow(jTableFormation.getSelectedRow());
            
        }
    }//GEN-LAST:event_b_deleteActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // Procédure pour mettre à jour un module 
        if(comboFormation.getSelectedItem().toString().equals("LICENCE 3")){
            Formation licence3 = Insert.Inserer();
        messageErreur.setText("");//Vider le label Message
        DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
        if(jTableFormation.getSelectedRow() == -1 ){
            if(jTableFormation.getRowCount() == 0){
                messageErreur.setText("WARNING UPDATE! La table est vide");
            }else {
                 messageErreur.setText("WARNING UPDATE! Vous devez selectionner au moins une ligne ");
            }
        }else {
            if(!textModule.getText().trim().equals("") && !textAbbrev.getText().trim().equals("") && !textNbSeance.getText().trim().equals("")){
        if(licence3.testUpdateNom(model.getValueAt(jTableFormation.getSelectedRow(),0).toString(),textModule.getText()) == 0){
        if(licence3.testUpdateAbbrev(model.getValueAt(jTableFormation.getSelectedRow(),0).toString(),textAbbrev.getText()) == 0){      
        if(licence3.testUpdateCouleur(model.getValueAt(jTableFormation.getSelectedRow(),0).toString(),comboCouleur.getSelectedItem().toString()) == 0 ){       
        model.setValueAt(textModule.getText(), jTableFormation.getSelectedRow(), 0);
        model.setValueAt(textAbbrev.getText(), jTableFormation.getSelectedRow(), 1);
        model.setValueAt(comboCouleur.getSelectedItem().toString(), jTableFormation.getSelectedRow(), 2);
        model.setValueAt(textNbSeance.getText(), jTableFormation.getSelectedRow(), 3);
       }else{
            messageErreur.setText("WARNING CHOIX COULEUR! cette couleur existe déja");
        }
        
        }else{
            messageErreur.setText("WARNING CHOIX ABBREVIATION! cette abbreviation existe déja");
        }
        
        
        }else{
             messageErreur.setText("WARNING CHOIX NOM! Ce nom existe déja");
        }
       }else {
                 messageErreur.setText("WARNING UPDATE! Veuillez remplir tous les champs ");
            }
        }
        }
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_sauveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sauveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_sauveActionPerformed

    private void comboCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCouleurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCouleurActionPerformed

    private void b_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_deleteMouseClicked
        
    }//GEN-LAST:event_b_deleteMouseClicked

    private void jTableFormationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFormationMouseClicked
       DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
        textModule.setText(model.getValueAt(jTableFormation.getSelectedRow(),0).toString());
        textAbbrev.setText(model.getValueAt(jTableFormation.getSelectedRow(),1).toString());
        comboCouleur.setSelectedItem(model.getValueAt(jTableFormation.getSelectedRow(),2).toString());
        textNbSeance.setText(model.getValueAt(jTableFormation.getSelectedRow(),3).toString());
    }//GEN-LAST:event_jTableFormationMouseClicked
// Choix de la formation 
    private void comboFormationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormationItemStateChanged
           msgNomFormation.setText("");
            msgDureeSeanceFormation.setText("");
            msgDureeFormation.setText("");
            
            
            DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
            deleteAllRows(model);
         //DefaultTableModel model = (DefaultTableModel) jTableFormation.getModel();
          
         if(comboFormation.getSelectedItem().toString().equals("LICENCE 3")){
           
            Formation licence3 = Insert.Inserer();
            msgNomFormation.setText("La Formation : "+licence3.getNom());
            double duree = licence3.getDureeSeance();
            int dureeInt = (int) duree;
            msgDureeSeanceFormation.setText("Durée type d'une seance : "+dureeInt+"h");
            msgDureeFormation.setText(licence3.afficherDureeFormation(licence3.DureeFormation()));
        
         for (int i = 0;i< licence3.getTabModule().size();i++){
             
         Module module = licence3.getTabModule().get(i).getModule();
         
         model.addRow(new Object[]{module.getNom(),module.getAbbrev(),module.getCouleur(),module.getNbSeance()});
         
         }
         }
    }//GEN-LAST:event_comboFormationItemStateChanged
    public static void deleteAllRows(final DefaultTableModel model) {
    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
        model.removeRow(i);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableCreaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableCreaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableCreaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableCreaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableCreaModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ajout;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_sauve;
    private javax.swing.JButton b_update;
    private javax.swing.JComboBox comboCouleur;
    private javax.swing.JComboBox comboFormation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFormation;
    private javax.swing.JLabel messageErreur;
    private javax.swing.JLabel msgDureeFormation;
    private javax.swing.JLabel msgDureeSeanceFormation;
    private javax.swing.JLabel msgNomFormation;
    private javax.swing.JTextField textAbbrev;
    private javax.swing.JTextField textModule;
    private javax.swing.JTextField textNbSeance;
    // End of variables declaration//GEN-END:variables
}
