/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JTableFenetres;
import Controller.Couleur;
import Modele.ForMod.*;
import Modele.Initialisation.*;
import Controller.ConditionAjoutSeance;

import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import Modele.Calendrier.*;


/**
 *
 * @author NadeemShia
 */
public class JTableAjoutModule extends javax.swing.JFrame {
//extends DefaultTableCellRenderer{
//extends javax.swing.JFrame {

    /**
     * Creates new form JTableBis
     */
    
    
    static Component  cell; 
    public JTableAjoutModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreFenetre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_ajout = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_save = new javax.swing.JButton();
        comboNomModule = new javax.swing.JComboBox();
        comboFormation = new javax.swing.JComboBox();
        comboH = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauSemaine = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        msgErreur = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        dateLundi = new javax.swing.JLabel();
        dateVendredi = new javax.swing.JLabel();
        dateMercredi = new javax.swing.JLabel();
        dateMardi = new javax.swing.JLabel();
        dateSamedi = new javax.swing.JLabel();
        dateDimanche = new javax.swing.JLabel();
        dateJeudi = new javax.swing.JLabel();
        bPrec = new javax.swing.JButton();
        bSuiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitreFenetre.setText("Fenêtre d'Ajout des Modules ");

        jLabel1.setText("Nom Module");

        jLabel2.setText("Jour");

        jLabel5.setText("Matin / apès-midi");

        b_ajout.setText("Ajouter");
        b_ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ajoutMouseClicked(evt);
            }
        });
        b_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ajoutActionPerformed(evt);
            }
        });

        b_delete.setText("Supprimer");
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        b_update.setText("Mettre à jour");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_save.setText("Sauvegarder");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        comboNomModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboNomModuleMouseClicked(evt);
            }
        });

        comboFormation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Licence 3" }));
        comboFormation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormationItemStateChanged(evt);
            }
        });

        comboH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matin", "Apres Midi" }));
        comboH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHActionPerformed(evt);
            }
        });

        tableauSemaine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tableauSemaine.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tableauSemaine.setForeground(new java.awt.Color(0, 0, 255));
        tableauSemaine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "LUNDI", "MARDI", "MERCREDI", "JEUDI", "VENDREDI", "SAMEDI", "DIMANCHE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableauSemaine.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        tableauSemaine.setGridColor(new java.awt.Color(0, 0, 0));
        tableauSemaine.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableauSemaine);
        if (tableauSemaine.getColumnModel().getColumnCount() > 0) {
            tableauSemaine.getColumnModel().getColumn(0).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(1).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(2).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(3).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(4).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(5).setResizable(false);
            tableauSemaine.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel3.setText("Formation");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Matin");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Après Midi");

        msgErreur.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        msgErreur.setForeground(new java.awt.Color(255, 51, 51));

        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dateMouseEntered(evt);
            }
        });

        bPrec.setText("Précendente");
        bPrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPrecMouseClicked(evt);
            }
        });

        bSuiv.setText("Suivante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_ajout)
                                .addGap(48, 48, 48)
                                .addComponent(b_delete)
                                .addGap(39, 39, 39)
                                .addComponent(b_update)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comboH, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(b_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bPrec))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(comboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNomModule, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bSuiv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(448, 448, 448)
                                        .addComponent(TitreFenetre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(231, 231, 231)
                                        .addComponent(msgErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dateLundi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(dateMardi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(dateMercredi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(dateJeudi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(dateVendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addComponent(dateSamedi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateDimanche, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TitreFenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboNomModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(comboH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ajout)
                    .addComponent(b_delete)
                    .addComponent(b_update)
                    .addComponent(b_save)
                    .addComponent(bPrec)
                    .addComponent(bSuiv))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLundi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateMardi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateMercredi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateSamedi)
                        .addComponent(dateDimanche)
                        .addComponent(dateVendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateJeudi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(msgErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_saveActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_updateActionPerformed

    private void b_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ajoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_ajoutActionPerformed

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_deleteActionPerformed

    private void comboNomModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboNomModuleMouseClicked
        
    }//GEN-LAST:event_comboNomModuleMouseClicked

    private void comboFormationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormationItemStateChanged
        DefaultTableModel model = (DefaultTableModel) tableauSemaine.getModel();
        model.setValueAt(Color.gray, 1,6);
         model.setValueAt(Color.gray, 0,6);
        model.setValueAt(Color.gray, 1,5);
          model.setValueAt(Color.gray, 0,5);
        msgErreur.setText("");
        comboNomModule.removeAllItems();
        if(comboFormation.getSelectedItem().toString().equals("Licence 3")){
        Formation licence3 = Insert.Inserer();
         for (int i = 0;i< licence3.getTabModule().size();i++){ 
         Module module = licence3.getTabModule().get(i).getModule();
         comboNomModule.addItem(module.getNom());
         
         }
         
        }
        else
            msgErreur.setText("Veuillez choisir une formation");
    }//GEN-LAST:event_comboFormationItemStateChanged

    private void comboHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHActionPerformed
       
    }//GEN-LAST:event_comboHActionPerformed

    private void b_ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ajoutMouseClicked
        String abb="";
        Date lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche;
     // Component  cell; 
        DefaultTableModel model = (DefaultTableModel) tableauSemaine.getModel();
//       model.setValueAt(Color.gray, 1,6);
//        model.setValueAt(Color.gray, 0,6);
//        model.setValueAt(Color.gray, 1,5);
//        model.setValueAt(Color.gray, 0,5);
//        lundi = Semaine.RecLundi(date.getDate());
//         dateLundi.setText(lundi.toLocaleString());
        
      
             //tableauSemaine.setDefaultRenderer(Color.class, new Couleur());
            // cell = Couleur.TableCellRendererComponent(tableauSemaine,"r", false , false, 0, 6);
         if(comboFormation.getSelectedItem().toString().equals("Licence 3")){
              GregorianCalendar calendar = new GregorianCalendar();
              calendar.setTime(date.getDate());
              int jour;
              jour = calendar.get(Calendar.DAY_OF_WEEK);
              lundi = Semaine.RecLundi(date.getDate());
              mardi = Semaine.RecDemain(lundi);
              mercredi = Semaine.RecDemain(mardi);
              jeudi = Semaine.RecDemain(mercredi);
              vendredi = Semaine.RecDemain(jeudi);
              samedi = Semaine.RecDemain(vendredi);
              dimanche = Semaine.RecDemain(samedi);
                dateLundi.setText(lundi.toLocaleString());
                dateMardi.setText(Semaine.RecDemain(lundi).toLocaleString());
                dateMercredi.setText(Semaine.RecDemain(mardi).toLocaleString());
                dateJeudi.setText(Semaine.RecDemain(mercredi).toLocaleString());
                dateVendredi.setText(Semaine.RecDemain(jeudi).toLocaleString());
                dateSamedi.setText(Semaine.RecDemain(vendredi).toLocaleString());
                dateDimanche.setText(Semaine.RecDemain(samedi).toLocaleString());
                
                
              if (jour == 1 || jour == 7){//si le jour en question (laDate from jDateChooser1) est un jour ferier
           msgErreur.setText("Il n'y a pas de cours les weekend, veuillez choisir un jour en semaine pour y ajouter le module.");}
              else{
             Formation licence3;
           
            licence3 = Insert.Inserer();
       //   abb = ConditionAjoutSeance.abbSeance(licence3,comboNomModule.getSelectedItem().toString());
         if(comboH.getSelectedItem().equals("Matin")){
           
             switch (jour)
            {
                 
            case 1: model.setValueAt(abb, 0,6);break; 
               
            case 2:   
                //Object obj = Couleur.setFormation(tableauSemaine,abb,2,2,abb);
                //seance.setBackground(Color.red);
                //tableauSemaine.setFont(new java.awt.Font("Lucida Grande",2,18));
               // tableauSemaine.setForeground(Color.red);
               
               model.setValueAt(Color.BLUE, 0,0);
                //model.setValueAt("rouge", 0,0);
//                tableauSemaine.setDefaultRenderer(Object.class, new Couleur());
                //model.setValueAt("rouge", 0,0);

                
            
            //tableauSemaine.setDefaultRenderer(Color.class, new Couleur());
            break;
              
            case 3: model.setValueAt(abb, 0,1);
             //tableauSemaine.setForeground(Color.blue);
            
           
            //tableauSemaine.setDefaultRenderer(Color.class, new Couleur());
            break;
            case 4: model.setValueAt(abb, 0,2);break;
            case 5: model.setValueAt(abb, 0,3);break;
            case 6: model.setValueAt(abb, 0,4);break;
            case 7: model.setValueAt(abb, 0,5);break;           
            }
            
         }else{
             switch (jour)
            {
            case 1: model.setValueAt(abb, 1,6);break; 
            case 2: model.setValueAt(abb, 1,0);break;
            case 3: model.setValueAt(abb, 1,1);break;
            case 4: model.setValueAt(abb, 1,2);break;
            case 5: model.setValueAt(abb, 1,3);break;
            case 6: model.setValueAt(abb, 1,4);break;
            case 7: model.setValueAt(abb, 1,5);break;           
            }
             
         }
         }
         }
         else
            msgErreur.setText("Veuillez choisir une formation");
              
    }//GEN-LAST:event_b_ajoutMouseClicked

    private void dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMousePressed
        // TODO add your handling code here:
//        Date lundi;
//         DefaultTableModel model = (DefaultTableModel) tableauSemaine.getModel();
//         model.setValueAt(Color.gray, 1,6);
//         model.setValueAt(Color.gray, 0,6);
//         model.setValueAt(Color.gray, 1,5);
//         model.setValueAt(Color.gray, 0,5);
//         
//         
//         lundi = Semaine.RecLundi(date.getDate());
//         dateLundi.setText(lundi.toLocaleString());
    }//GEN-LAST:event_dateMousePressed

    private void dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseEntered
        // TODO add your handling code here:
//         Date lundi;
//         DefaultTableModel model = (DefaultTableModel) tableauSemaine.getModel();
//         model.setValueAt(Color.gray, 1,6);
//         model.setValueAt(Color.gray, 0,6);
//         model.setValueAt(Color.gray, 1,5);
//         model.setValueAt(Color.gray, 0,5);
//         
//         
//         lundi = Semaine.RecLundi(date.getDate());
//         dateLundi.setText(lundi.toLocaleString());
    }//GEN-LAST:event_dateMouseEntered

    private void bPrecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPrecMouseClicked
        // TODO add your handling code here:
        Date lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche;
//         GregorianCalendar calendar = new GregorianCalendar();
//              calendar.setTime(date.getDate());
//              int jour;
//              jour = calendar.get(Calendar.DAY_OF_WEEK);
              lundi = Semaine.RecLundiPreced(date.getDate());
              mardi = Semaine.RecDemain(lundi);
              mercredi = Semaine.RecDemain(mardi);
              jeudi = Semaine.RecDemain(mercredi);
              vendredi = Semaine.RecDemain(jeudi);
              samedi = Semaine.RecDemain(vendredi);
              dimanche = Semaine.RecDemain(samedi);
                dateLundi.setText(lundi.toLocaleString());
                dateMardi.setText(Semaine.RecDemain(lundi).toLocaleString());
                dateMercredi.setText(Semaine.RecDemain(mardi).toLocaleString());
                dateJeudi.setText(Semaine.RecDemain(mercredi).toLocaleString());
                dateVendredi.setText(Semaine.RecDemain(jeudi).toLocaleString());
                dateSamedi.setText(Semaine.RecDemain(vendredi).toLocaleString());
                dateDimanche.setText(Semaine.RecDemain(samedi).toLocaleString());
        
    }//GEN-LAST:event_bPrecMouseClicked

  

     
     
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTableAjoutModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTableAjoutModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTableAjoutModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableAjoutModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JTableAjoutModule().setVisible(true);
                
                JTableAjoutModule jtable = new JTableAjoutModule();
                
                jtable.tableauSemaine.setRowHeight(96);
                jtable.tableauSemaine.setDefaultRenderer(Object.class,new Couleur());
          
                //jtable.tableauSemaine.setGridColor(Color.RED);
                //jtable.tableauSemaine.setBackground(Color.BLACK);
               //jtable.tableauSemaine.setDefaultRenderer(Color.class, new Couleur());
                jtable.setVisible(true); 
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitreFenetre;
    private javax.swing.JButton bPrec;
    private javax.swing.JButton bSuiv;
    private javax.swing.JButton b_ajout;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_save;
    private javax.swing.JButton b_update;
    private javax.swing.JComboBox comboFormation;
    private javax.swing.JComboBox comboH;
    private javax.swing.JComboBox comboNomModule;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel dateDimanche;
    private javax.swing.JLabel dateJeudi;
    private javax.swing.JLabel dateLundi;
    private javax.swing.JLabel dateMardi;
    private javax.swing.JLabel dateMercredi;
    private javax.swing.JLabel dateSamedi;
    private javax.swing.JLabel dateVendredi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgErreur;
    private javax.swing.JTable tableauSemaine;
    // End of variables declaration//GEN-END:variables
}
